# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Z7.xdc

# Block Designs: bd/SonarProjectSV/SonarProjectSV.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV || ORIG_REF_NAME==SonarProjectSV} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_processing_system7_0_0/SonarProjectSV_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_processing_system7_0_0 || ORIG_REF_NAME==SonarProjectSV_processing_system7_0_0} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_PmodMAXSONAR_0_0/SonarProjectSV_PmodMAXSONAR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_PmodMAXSONAR_0_0 || ORIG_REF_NAME==SonarProjectSV_PmodMAXSONAR_0_0} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_PmodOLEDrgb_0_0/SonarProjectSV_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_PmodOLEDrgb_0_0 || ORIG_REF_NAME==SonarProjectSV_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_axi_smc_0/SonarProjectSV_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_axi_smc_0 || ORIG_REF_NAME==SonarProjectSV_axi_smc_0} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_rst_ps7_0_50M_0/SonarProjectSV_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_rst_ps7_0_50M_0 || ORIG_REF_NAME==SonarProjectSV_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/SonarProjectSV/ip/SonarProjectSV_axi_gpio_0_0/SonarProjectSV_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SonarProjectSV_axi_gpio_0_0 || ORIG_REF_NAME==SonarProjectSV_axi_gpio_0_0} -quiet] -quiet

# XDC: f:/FPGA_Project/SonarProjectSV/SonarProjectSV.gen/sources_1/bd/SonarProjectSV/SonarProjectSV_ooc.xdc
